### PR TITLE
127.0.0.1 is the default

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by jlahav** [comment]
Hi

Thank you for the pull request but this makes no sense for now.

JHI connects through socket only to a virtualized FW (such as the SDK), and no virtualized FW can run on Linux. The most common scenario is to run JHI in a Linux VM on a Windows host, run the SDK emulator on the host, and connect JHI to the host emulator. The default IP in the config is the default VirtualBox host IP in NAT config.

Let me know if I missed something.

**Comment by mitar** [comment]
I mean, I made this because [comment is saying that this is the default](https://github.com/mitar/dynamic-application-loader-host-interface/blob/35da9c9f873a6f96750ff1f9d5557aa4a1470c21/service/linux/jhi.conf#L26).

I have no idea what this repo is about. There is no README. So I do not know how it is expected to be used. I came here from [SGX repo](https://github.com/01org/linux-sgx) where it says [I should install this repo](https://github.com/01org/linux-sgx#prerequisites-2). There, I have only Linux machine with SGX, wanting to use Linux only. No Windows. What it says there install this repo and run it. But to me to run it there is no point in running it on an IP I do not have/use.

So, what is this repo about, why it is needed for SGX, and why localhost would not be a reasonable setting when used with SGX on Linux?

**Comment by jlahav** [comment]
Ah, you're correct. The comment is wrong. I'll change it. Thanks for noticing.

The readme is almost ready, will be uploaded soon.

The IP is not relevant for you as [you don't configure JHI to connect over a socket](https://github.com/01org/dynamic-application-loader-host-interface/blob/master/service/linux/jhi.conf#L28).

JHI (this repo) is a service/daemon that allows connection to Intel DAL. It multiplexes the FW connection and formats packages correctly.

**Comment by mitar** [comment]
Oh, good. Thanks. Then I do not have to worry about it. :-)

**Comment by jlahav** [comment]
I checked and I was mistaken, the comment was correct.
Default means that if you don't configure an IP, localhost will be used.
For convenience, a value which fits a common use case is preset in the config.

**Comment by mitar** [comment]
But isn't it normal that default values in settings (those uncommented) follow the default values? If I run the program with default config files I would assume it will use default settings.

**Pull request closed without merging**
